name: deploy.yml
on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (ัะบ nvm use)
        uses: actions/setup-node@v4
        with:
          node-version: '24.4.1'

      - name: Install dependencies
        run: |
          node -v
          echo "running npm install"
          npm install

      - name: Export web
        run: npx expo export --platform web


      - name: Setup SSH
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KNOWN_HOST }}" >> ~/.ssh/known_hosts

      - name: Check known_hosts content
        run: cat ~/.ssh/known_hosts

      - name: Check SSH key
        run: cat key.pem

      - name: Download build files to server
        run: |
          ssh -i key.pem -o UserKnownHostsFile=$HOME/.ssh/known_hosts ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
            rm -rf /home/${{ secrets.DEPLOY_USER }}/neuer-standard/web_tmp/ &&
            mkdir -p /home/${{ secrets.DEPLOY_USER }}/neuer-standard/web_tmp/
          '
          scp -i key.pem -o UserKnownHostsFile=$HOME/.ssh/known_hosts -r dist/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/home/${{ secrets.DEPLOY_USER }}/neuer-standard/web_tmp/
          ssh -i key.pem -o UserKnownHostsFile=$HOME/.ssh/known_hosts ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
            rm -rf /home/${{ secrets.DEPLOY_USER }}/neuer-standard/web_old/ &&
            mv /var/www/nginx/neuer-standard /home/${{ secrets.DEPLOY_USER }}/neuer-standard/web_old/ &&
            mv /home/${{ secrets.DEPLOY_USER }}/neuer-standard/web_tmp/ /var/www/nginx/neuer-standard/ &&
            rm -rf /home/${{ secrets.DEPLOY_USER }}/neuer-standard/web_old/
          '
      



